/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiArtifactsRouteImport } from './routes/api.artifacts'
import { Route as ApiPlayerRouteImport } from './routes/api.player'
import { Route as ApiPreviewRouteImport } from './routes/api.preview'
import { Route as ApiRunRouteImport } from './routes/api.run'
import { Route as PSplatRouteImport } from './routes/p.$'
import { Route as RSplatRouteImport } from './routes/r.$'
import { Route as ApiUploadsRunIdNameRouteImport } from './routes/api.uploads.$runId.$name'
import { Route as ApiPlayerMediaThreadKeyPortProjectSplatRouteImport } from './routes/api.player.media.$threadKey.$port.$project.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArtifactsRoute = ApiArtifactsRouteImport.update({
  id: '/api/artifacts',
  path: '/api/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayerRoute = ApiPlayerRouteImport.update({
  id: '/api/player',
  path: '/api/player',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreviewRoute = ApiPreviewRouteImport.update({
  id: '/api/preview',
  path: '/api/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunRoute = ApiRunRouteImport.update({
  id: '/api/run',
  path: '/api/run',
  getParentRoute: () => rootRouteImport,
} as any)
const PSplatRoute = PSplatRouteImport.update({
  id: '/p/$',
  path: '/p/$',
  getParentRoute: () => rootRouteImport,
} as any)
const RSplatRoute = RSplatRouteImport.update({
  id: '/r/$',
  path: '/r/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsRunIdNameRoute = ApiUploadsRunIdNameRouteImport.update({
  id: '/api/uploads/$runId/$name',
  path: '/api/uploads/$runId/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayerMediaThreadKeyPortProjectSplatRoute =
  ApiPlayerMediaThreadKeyPortProjectSplatRouteImport.update({
    id: '/media/$threadKey/$port/$project/$',
    path: '/media/$threadKey/$port/$project/$',
    getParentRoute: () => ApiPlayerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/artifacts': typeof ApiArtifactsRoute
  '/api/player': typeof ApiPlayerRouteWithChildren
  '/api/preview': typeof ApiPreviewRoute
  '/api/run': typeof ApiRunRoute
  '/p/$': typeof PSplatRoute
  '/r/$': typeof RSplatRoute
  '/api/uploads/$runId/$name': typeof ApiUploadsRunIdNameRoute
  '/api/player/media/$threadKey/$port/$project/$': typeof ApiPlayerMediaThreadKeyPortProjectSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/artifacts': typeof ApiArtifactsRoute
  '/api/player': typeof ApiPlayerRouteWithChildren
  '/api/preview': typeof ApiPreviewRoute
  '/api/run': typeof ApiRunRoute
  '/p/$': typeof PSplatRoute
  '/r/$': typeof RSplatRoute
  '/api/uploads/$runId/$name': typeof ApiUploadsRunIdNameRoute
  '/api/player/media/$threadKey/$port/$project/$': typeof ApiPlayerMediaThreadKeyPortProjectSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/artifacts': typeof ApiArtifactsRoute
  '/api/player': typeof ApiPlayerRouteWithChildren
  '/api/preview': typeof ApiPreviewRoute
  '/api/run': typeof ApiRunRoute
  '/p/$': typeof PSplatRoute
  '/r/$': typeof RSplatRoute
  '/api/uploads/$runId/$name': typeof ApiUploadsRunIdNameRoute
  '/api/player/media/$threadKey/$port/$project/$': typeof ApiPlayerMediaThreadKeyPortProjectSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/artifacts'
    | '/api/player'
    | '/api/preview'
    | '/api/run'
    | '/p/$'
    | '/r/$'
    | '/api/uploads/$runId/$name'
    | '/api/player/media/$threadKey/$port/$project/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/artifacts'
    | '/api/player'
    | '/api/preview'
    | '/api/run'
    | '/p/$'
    | '/r/$'
    | '/api/uploads/$runId/$name'
    | '/api/player/media/$threadKey/$port/$project/$'
  id:
    | '__root__'
    | '/'
    | '/api/artifacts'
    | '/api/player'
    | '/api/preview'
    | '/api/run'
    | '/p/$'
    | '/r/$'
    | '/api/uploads/$runId/$name'
    | '/api/player/media/$threadKey/$port/$project/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiArtifactsRoute: typeof ApiArtifactsRoute
  ApiPlayerRoute: typeof ApiPlayerRouteWithChildren
  ApiPreviewRoute: typeof ApiPreviewRoute
  ApiRunRoute: typeof ApiRunRoute
  PSplatRoute: typeof PSplatRoute
  RSplatRoute: typeof RSplatRoute
  ApiUploadsRunIdNameRoute: typeof ApiUploadsRunIdNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/artifacts': {
      id: '/api/artifacts'
      path: '/api/artifacts'
      fullPath: '/api/artifacts'
      preLoaderRoute: typeof ApiArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/player': {
      id: '/api/player'
      path: '/api/player'
      fullPath: '/api/player'
      preLoaderRoute: typeof ApiPlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preview': {
      id: '/api/preview'
      path: '/api/preview'
      fullPath: '/api/preview'
      preLoaderRoute: typeof ApiPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/run': {
      id: '/api/run'
      path: '/api/run'
      fullPath: '/api/run'
      preLoaderRoute: typeof ApiRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$': {
      id: '/p/$'
      path: '/p/$'
      fullPath: '/p/$'
      preLoaderRoute: typeof PSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$': {
      id: '/r/$'
      path: '/r/$'
      fullPath: '/r/$'
      preLoaderRoute: typeof RSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/$runId/$name': {
      id: '/api/uploads/$runId/$name'
      path: '/api/uploads/$runId/$name'
      fullPath: '/api/uploads/$runId/$name'
      preLoaderRoute: typeof ApiUploadsRunIdNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/player/media/$threadKey/$port/$project/$': {
      id: '/api/player/media/$threadKey/$port/$project/$'
      path: '/media/$threadKey/$port/$project/$'
      fullPath: '/api/player/media/$threadKey/$port/$project/$'
      preLoaderRoute: typeof ApiPlayerMediaThreadKeyPortProjectSplatRouteImport
      parentRoute: typeof ApiPlayerRoute
    }
  }
}

interface ApiPlayerRouteChildren {
  ApiPlayerMediaThreadKeyPortProjectSplatRoute: typeof ApiPlayerMediaThreadKeyPortProjectSplatRoute
}

const ApiPlayerRouteChildren: ApiPlayerRouteChildren = {
  ApiPlayerMediaThreadKeyPortProjectSplatRoute:
    ApiPlayerMediaThreadKeyPortProjectSplatRoute,
}

const ApiPlayerRouteWithChildren = ApiPlayerRoute._addFileChildren(
  ApiPlayerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiArtifactsRoute: ApiArtifactsRoute,
  ApiPlayerRoute: ApiPlayerRouteWithChildren,
  ApiPreviewRoute: ApiPreviewRoute,
  ApiRunRoute: ApiRunRoute,
  PSplatRoute: PSplatRoute,
  RSplatRoute: RSplatRoute,
  ApiUploadsRunIdNameRoute: ApiUploadsRunIdNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
